apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-nodeport # service 이름
  namespace: wsscc2021 # service가 속할 namespace
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kubia
    # service의 파드 셀렉터는 엔드포인트 목록을 만드는 데 사용됩니다.
  ports:
    - protocol: TCP
      port: 80 # 서비스 내부의 clsuterip 포트번호
      targetPort: 8080 # pod의 포트번호
      nodePort: 30123 # 클러스터 노드의 포트 30123으로 서비스에 액세스 가능