apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-api
  namespace: dev
spec:
  replicas: 6
  selector:
    matchLabels: # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
      app.kubernetes.io/name: foo-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foo-api
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: "ScheduleAnyway" # "DoNotSchedule", "ScheduleAnyway"
          labelSelector:
            app.kubernetes.io/name: "foo-api"
      containers:
        - image: 242593025403.dkr.ecr.us-east-1.amazonaws.com/foo-api:v1
          name: foo-api
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 820m
              memory: 1000Mi
            requests:
              cpu: 820m
              memory: 1000Mi
      terminationGracePeriodSeconds: 60