apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<<account-id>>:role/<<node-group-role-name>>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::<<account-id>>:role/<<admin-role-name>>
      username: role:<<admin-role-name>>
      groups:
        - system:masters
  mapUsers: |
    - userarn:arn:aws:iam::<<account-id>>:root
      username: root
      groups:
        - system:masters
    - userarn:arn:aws:iam::<<account-id>>:<<admin-username>>
      username: <<admin-username>>
      groups:
        - system:masters