apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::242593025403:role/dev-worldskills-role-nodegroup
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::242593025403:role/AdministratorRole
      username: role:AdministratorRole
      groups:
        - system:masters
  mapUsers: |
    - userarn:arn:aws:iam::242593025403:root
      username: root
      groups:
        - system:masters