apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job # job 이름
  namespace: wsscc2021 # job이 속할 namespace
spec:
  completions: 5 # default 1, job을 n번 성공하도록 실행합니다.
  parallelism: 2 # default 1, job을 동시에 n개의 파드로 진행합니다.
  backoffLimit: 3 
  # 재시도 횟수를 제한합니다. n번 이상 실패할 경우 더 이상 파드를 실행하지 않습니다.
  # 만약 pod의 restartPolicy가 OnFailure로 지정되어 있다면, pod가 전부 삭제됩니다. 이는 필요없는 리소스를 남겨두지 않습니다.
  # 만약 pod의 restartPolicy가 Never로 설정되어 있다면, pod가 삭제되지 않습니다. 이는 실패 원인을 조사할 때 유용합니다.
  activeDeadlineSeconds: 100 # 실행시간을 제한합니다. n초 이상 실행되면 실패 처리합니다.
  template: # job으로 생성될 pod를 정의합니다.
    metadata:
      labels: # job으로 생성될 pod의 label을 작성합니다.
        app.kubernetes.io/name: kubia
        # kubernetes 권장 레이블을 참조하면 좋습니다.
        # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
    spec:
      restartPolicy: Never
      # 재시작 정책을 작성합니다.
      # OnFailure, Always, Never 중 하나를 선택할 수 있으며, 기본값은 Always 입니다.
      # Job의 경우 OnFailure를 통해 장애가 발생하였을 경우에만 재시작하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-lifecycle/#%EC%9E%AC%EC%8B%9C%EC%9E%91-%EC%A0%95%EC%B1%85
      containers:
      - name: main
        image: luksa/batch-job