apiVersion: v1
kind: Pod
metadata:
  name: kubia
  namespace: dev
  labels:
    app.kubernetes.io/name: kubia
    app.kubernetes.io/version: v1
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP