apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-nodeport
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: kubia
    app.kubernetes.io/version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30123