apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-clusterip
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: kubia
    app.kubernetes.io/version: v1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080