apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-clusterip # service 이름
  namespace: wsscc2021 # service가 속할 namespace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubia
    # service의 파드 셀렉터는 엔드포인트 목록을 만드는 데 사용됩니다.
  ports:
    - protocol: TCP
      port: 80 # 서비스의 포트번호
      targetPort: 8080 # pod의 포트번호