apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-loadbalancer # service 이름
  namespace: wsscc2021 # service가 속할 namespace
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # Local,Cluster
  # Local: node 내에 있는 pod에만 접근할 수 있도록 하여 불필요한 네트워크 홉을 줄여준다.
  # Cluster: 다른 node의 pod로도 접근할 수 있다.
  selector:
    app.kubernetes.io/name: kubia
    # service의 파드 셀렉터는 엔드포인트 목록을 만드는 데 사용됩니다.
  ports:
    - protocol: TCP
      port: 80 # 서비스 내부의 clsuterip 포트번호
      targetPort: 8080 # pod의 포트번호