apiVersion: v1
kind: Pod
metadata:
  name: mongodb-aws-ebs # Pod 이름
  namespace: wsscc2021 # Pod가 속할 namespace
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  # 같은 AZ에 있는 EBS Volume만 마운트할 수 있습니다.
  # 생성된 EBS Volume과 같은 AZ에 파드가 생성되도록 nodeSelector를 사용합니다.
  volumes:
  - name: mongodb-data # Volume 이름
    awsElasticBlockStore:
      volumeID: vol-07c06b666e31dd845 # aws ebs volume-id
      fsType: ext4 # filesystem
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data # 마운트할 Volume 이름을 지정합니다.
      mountPath: /data/db # Container의 마운트 경로를 설정합니다.
    ports:
      - containerPort: 27017
        protocol: TCP
      # 어플리케이션이 수신하는 포트
      # 어플리케이션에서 0.0.0.0 으로 노출시켰다면 생략해도 되지만, 
      # 명시적으로 작성하는 것이 좋습니다.
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/