apiVersion: v1
kind: Pod
metadata:
  name: fortune # pod 이름
  namespace: wsscc2021 # pod가 속할 namespace
spec:
  volumes: # Volume을 정의합니다.
  - name: html # Volume 이름
    emptyDir: {}
  # emptyDir은 파드가 종료되면 삭제되는 임시 저장소 입니다.
  containers:
  - image: luksa/fortune
    name: html-generator
    volumeMounts:
    - name: html # mount할 volume이름을 지정합니다.
      mountPath: /var/htdocs # mount할 container의 경로를 작성합니다.
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html # mount할 volume이름을 지정합니다.
      mountPath: /usr/share/nginx/html # mount할 container의 경로를 작성합니다.
      readOnly: true # 읽기전용으로 mount합니다.
    ports:
      - containerPort: 80
        protocol: TCP
        # 어플리케이션이 수신하는 포트
        # 어플리케이션에서 0.0.0.0 으로 노출시켰다면 생략해도 되지만, 
        # 명시적으로 작성하는 것이 좋습니다.
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/