apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  namespace: dev
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%" # integer(5) or percent(10%), default is 25%
      maxUnavailable: "25%" # integer(5) or percent(10%), default is 25%
  progressDeadlineSeconds: 600 # default is 600
  minReadySeconds: 0 # default is 0
  selector:
    matchLabels: # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
      app.kubernetes.io/name: kubia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubia
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: "ScheduleAnyway" # "DoNotSchedule", "ScheduleAnyway"
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: kubia
      tolerations:
        - key: "Management"
          operator: "Equal"       # "Equal", "Exists"
          value: "Apps"           # operator가 "Equal"인 경우에만 사용합니다.
          effect: "NoSchedule"    # "NoSchedule", "PreferNoSchedule", "NoExecute"
      containers:
        - image: luksa/kubia:2.0
          name: webapp
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 820m
              memory: 1000Mi
            requests:
              cpu: 820m
              memory: 1000Mi
      terminationGracePeriodSeconds: 60