apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels: # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
      app.kubernetes.io/name: shop-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shop-app
    spec:
      containers:
        - image: 733038577741.dkr.ecr.ap-southeast-1.amazonaws.com/wsi-ecr:2021-08-24.070417
          name: shop-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 820m
              memory: 1000Mi
            requests:
              cpu: 820m
              memory: 1000Mi
      terminationGracePeriodSeconds: 60