apiVersion: v1
kind: Pod
metadata:
  name: mongodb 
spec:
  volumes:
  - name: mongodb-data # Volume 이름
    persistentVolumeClaim: # PVC 연결
      claimName: mongodb-pvc # 연결할 PVC 이름
  containers:
  - image: mongo # 컨테이너 이미지
    name: mongodb # 컨테이너 이름
    volumeMounts: 
    - name: mongodb-data # 마운트할 Volume 이름
      mountPath: /data/db # 컨테이너의 Mount 경로
    ports:
    - containerPort: 27017
      protocol: TCP
      # 어플리케이션이 수신하는 포트
      # 어플리케이션에서 0.0.0.0 으로 노출시켰다면 생략해도 되지만, 
      # 명시적으로 작성하는 것이 좋습니다.
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/