apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume
spec:
  volumes:
  - name: html # volume 이름
    emptyDir: {}
  - name: config # volume 이름
    configMap:   # configmap volume 설정
      name: fortune-config # 가져올 configmap 이름
  containers:
  - name: html-generator
    image: luksa/fortune:env
    env:
    - name: INTERVAL
      valueFrom: # configmap으로부터 값을 가져옵니다.
        configMapKeyRef:
          name: fortune-config # 가져올 configmap 이름
          key: sleep-interval  # configmap 내의 key 이름
    volumeMounts:
    - name: html # 마운트할 volume 이름
      mountPath: /var/htdocs # 마운트 경로
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/
  - name: web-server
    image: nginx:alpine
    volumeMounts:
    - name: html # 마운트할 volume 이름
      mountPath: /usr/share/nginx/html # 마운트 경로
      readOnly: true
    - name: config # 마운트할 volume 이름
      mountPath: /etc/nginx/conf.d # 마운트 경로
      readOnly: true
    - name: config # 마운트할 volume 이름
      mountPath: /tmp/whole-fortune-config-volume # 마운트 경로
      readOnly: true
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/
