apiVersion: v1
kind: ConfigMap
metadata:
  name: fortune-config
data:
  sleep-interval: "25"
  my-nginx-config.conf: |
    server {
      listen              80;
      listen              443 ssl;
      server_name         www.kubia-example.com;

      ssl_certificate     certs/https.cert;
      ssl_certificate_key certs/https.key;
      ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;
      
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-https-pod # 파드 이름
  namespace: wsscc2021 # 파드가 속할 namespace
  labels:
    app.kubernetes.io/name: fortune
    # 레이블을 지정합니다.
    # kubernetes 권장 레이블을 참조하면 좋습니다.
    # https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/common-labels/
spec:
  volumes:
  - name: html
    emptyDir: {}
  - name: config # volume 이름
    configMap:   # configmap volume 설정
      name: fortune-config # 가져올 configmap 이름
      items:
        - key: my-nginx-config.conf
          path: https-config.conf
  - name: certs # volume 이름
    secret:     # secret volume 설정
      secretName: fortune-https # 가져올 secret 이름
  containers:
  - name: html-generator
    image: luksa/fortune:env
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef:
          name: fortune-config # configmap 이름
          key: sleep-interval # configmap 내 key 이름
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d/
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
      # requests,limits값을 동일하게 주어 Guaranteed class로 실행하는 것이 좋습니다.
      # Guaranteed class는 pod 축출 시 후순위 파드가 됩니다.
      # QoS에 대한 자세한 내용을 kubernetes 페이지에서 참조하는 것이 좋습니다.
      # https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/